.TH "PBAKER" "8" "June 14 2013" "dev@augmentedlogic.com" "pbaker"
.SH "NAME"
pbaker \- split large panorama images into tiles for use with openlayers
.SH "SYNOPSIS"
.B chwurz <option(s)>

.SH "DESCRIPTION"
split large panorama images into tiles for use with openlayers
.LP
.B 


.SH "OPTIONS"
\-i , \-\-image
.RS
<path/to/image> image file
.RE

\-t , \-\-target
.RS
<path/to/directory> target directory
.RE


\-f , \-\-format
.RS
<image format>, default is "jpg"
.RE


\-q , \-\-quiet
.RS
be quiet
.RE


\-m , \-\-imtmp
.RS
set the imagemagick temporary directory
.RE


\-h , \-\-help 
.RS
prints this help
.RE


.SH "BUGS"


.SH "AUTHORS"
augmented logic <dev@augmentedlogic.com>
.PP
man page by augmented logic



